name: Node CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest , macos-latest]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing dependencies
      run: |
        npm i
    - name: Building the interface
      run: |
        npm run build:tasks
        npm run build:webpack
    - name: Get packageJSON version
      id: package-node-version
      uses: culshaw/read-package-node-version-actions@v1
    - name: 'Creating release'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ steps.package-node-version.outputs.version }}
        prerelease: true
        title: "Unstable v${{ steps.package-node-version.outputs.version}}"
    - name : Creating the installer
      run: |
        npm run build:electron
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name : Building for RPM
      if: ${{ runner.os == 'Linux' }}
      run: |
        npm run build:electron:rpm
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}